# Generated by Django 6.1 on 2026-09-29 18:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('painel', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pedido',
            name='usuario',
            field=models.CharField(default=1, max_length=200),
            preserve_default=False,
        ),
    ]
