# Generated by Django 6.1 on 2026-09-03 00:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='twofactorcode',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
