# Generated by Django 6.1 on 2026-09-09 14:29

from django.db import migrations

def criar_grupos_acesso(apps, schema_editor):
    # Recupera o modelo Group nativo do Django
    Group = apps.get_model('auth', 'Group')
    
    # Lista com os nomes exatos dos grupos definidos na estrutura de views
    nomes_grupos = [
        'administradores',
        'diretoria',
        'gerencia_geral',
        'gerencia',
        'supervisao',
        'atendente',
        'caixa'
    ]
    
    # Cria cada grupo no banco de dados se ele não existir
    for nome in nomes_grupos:
        Group.objects.get_or_create(name=nome)

def remover_grupos_acesso(apps, schema_editor):
    # Função para permitir o rollback (reverter a migration se necessário)
    Group = apps.get_model('auth', 'Group')
    nomes_grupos = ['administradores', 'diretoria', 'gerencia_geral', 'gerencia', 'supervisao', 'atendente', 'caixa']
    
    # Remove os grupos criados
    Group.objects.filter(name__in=nomes_grupos).delete()


class Migration(migrations.Migration):

    dependencies = [
        # O Django preenche essa dependência automaticamente apontando para a migration anterior
        ('login', '0001_initial'), 
        ('auth', '0001_initial'), # Garante que o app auth do Django já foi migrado
    ]

    operations = [
        migrations.RunPython(criar_grupos_acesso, reverse_code=remover_grupos_acesso),
    ]