# Generated by Django 6.0.7 on 2026-09-09 22:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0003_alter_twofactorcode_user'),
        ('login', '0004_auto_20260909_1950'),
    ]

    operations = [
    ]
